name: Sync WWAN Files Only

on:
  workflow_dispatch:

jobs:
  sync_wwan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone source repo
        run: |
          git clone --depth=1 --branch NSS-12.5-K6.x-wwan https://github.com/qosmio/nss-packages temp-nss

      - name: Copy contents of 'wwan' folder only (not folder itself)
        run: |
          cp -rf temp-nss/wwan/* .

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git diff --cached --quiet || git commit -m "Sync: copy WWAN files from qosmio/NSS-12.5-K6.x-wwan"
          git push
